name: 1 - Hello World Github Actions

on:
  push: #git push
    branch:
      - main #trigger on main branch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello there
        run: echo "hello"