name: 3 - Test Django Env Vars

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - run: |
          echo "DJANGO_SECRET_KEY is set to ${DJANGO_SECRET_KEY:0:5}******"  # Print first 5 characters
      - run: |
          python manage.py test
        working-directory: ./src
      - name: Cleanup
        run: |
          find /tmp -type f -name '*.pyc' -delete
          rm -rf /tmp/__pycache__
      - name: Handle Test Failures
        if: steps.Django\ Tests.outcome != 'success'
        run: |
          echo "Tests failed. Check logs for details."
          exit 1